# Generated by Django 4.1.2 on 2022-10-16 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('ISBN', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='True')),
                ('images', models.ImageField(null=True, upload_to='imagenes/', verbose_name='Images')),
                ('description', models.TextField(null=True, verbose_name='Description')),
            ],
        ),
    ]
