# Generated by Django 4.1.2 on 2022-10-17 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0002_alter_libro_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='description',
            field=models.TextField(max_length=500, verbose_name='Description'),
        ),
    ]
